### PR TITLE
Much small things for better code quality

### PR DESCRIPTION
**Pull request by ololosha228**
List of all features of this branch:

* Constant oscillator
* Golangci config
* MIT License
* Fixed `NoteToPitch` for better performance
* fix a bunch of `go vet` warnings like using `copy()` instead `for` loop, etc.
* refactored tests of `theory` package, now it does looks cool, ready for add more testcases etc.

### CODE REVIEW

**Comment by bspaans** [comment]
Hey Richard, thanks for the contribution. I appreciate it, but there's quite a lot of different things here and the intent behind a few of these changes is not directly clear to me and would break some of my downstream projects that use bleep. I know it's a bit of a pain, but would you mind splitting this up into separate PRs? For breaking changes we'd also have an issue to reference and discuss beforehand ideally so that we can potentially avoid writing needless code. I'll put a note in the README as well, because I just put this on Github and ran off not expecting anything so I'm sorry for wasting your time.

**Comment by ololosha228** [comment]
@bspaans i'm very sad to hear that, but i appreciate too for your work, cause this lib has much of useful concepts even not so well documented :upside_down_face: 

Could you please allow me to fork this package and work on it separately of your main repo? I must ask you, cause there is no any license file in repository, so i wonder that forking this one is not so legal until i ask you)

**Comment by ololosha228** [comment]
Also, i've had a lot of problems and bugs with many methods and implementation of concepts, like [this one](https://github.com/bspaans/bleep/blob/master/filters/equalizer.go) (too funny to find this one "geniously-easy" implementation honestly :rofl: :rofl: :rofl:)

**Comment by bspaans** [comment]
> Could you please allow me to fork this package and work on it separately of your main repo? I must ask you, cause there is no any license file in repository, so i wonder that forking this one is not so legal until i ask you)

Absolutely! I've also added the MIT license now so you can do whatever you want with it basically.

**Pull request closed without merging**
